name = "english-practice"
type = "service"
main = "functions/api/[[route]].js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "STORE"
id = "english-practice-kv"
preview_id = "english-practice-kv-preview"
