name = "english-practice"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[env.production.kv_namespaces]]
binding = "KV_STORE"
id = "74bccb4f796240cf911adf4ff050d992"
preview_id = "74bccb4f796240cf911adf4ff050d992"
